name: 🔨🧪 Build & Test

permissions: write-all

on:
  pull_request:
    branches:
      - "main"

jobs:
  clientTest:
    name: 🧪 Client Test
    uses: ./.github/workflows/__client_test.yml
    secrets: inherit
  clientDeploy:
    name: 🔨 Client Deploy
    uses: ./.github/workflows/__client_deploy.yml
    secrets: inherit

  serverTest:
    name: 🧪 Server Test
    uses: ./.github/workflows/__server_test.yml
    secrets: inherit
